on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          mkdir -p ./be/src/main/resources
          cd ./be/src/main/resources
          touch ./application.yml
          echo "${{ secrets.PROPERTIES }}" | base64 --decode > ./application.yml
          find ./application.yml
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: be

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: be

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deployment
          cp be/build/libs/app.jar deployment/app.jar
          cd deployment && zip -r app-${{ steps.current-time.outputs.formattedTime }} .

      - name: Deploy Hello GitHub Action to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:		
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: shopping-mall-api-app
          environment_name: Shopping-mall-api-app-env
          version_label: app-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: deployment/app-${{ steps.current-time.outputs.formattedTime }}.zip
