on: 
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: make application.yml
      run: echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.yml
      
    - name: Build with Gradle
      uses: gradle/gradle@v3
      with:
        arguments: clean build bootJar

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDDTHHmm
        utcOffset: "+09:00"

    - name: Generate deployment package
      run: |
        mkdir -p deployment
        cp build/libs/app.jar deployment/app.jar
        cd deployment && zip -r app-${{ steps.current-time.outputs.formattedTime }} .
	ls

    - name: Deploy Hello Githup Action to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: [AWS 빈스톡 애플리케이션 이름]
        environment_name: [AWS 빈스톡 애플리케이션 환경 이름]
        version_label: app-${{ steps.current-time.outputs.formattedTime }}
        region: ap-northeast-2
        deployment_package: deployment/app-${{ steps.current-time.outputs.formattedTime }}.zip
